# Generated by Django 2.0.5 on 2018-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('visited_date', models.DateTimeField()),
                ('transport', models.CharField(default='bus', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
